/**
 * Compiles a validated filter
 * graph into a single fused WGSL compute pass plus pipeline.json.
 *
 * v1 scope: inline-fusable color/math chains (Source → … → Output). Nodes that
 * require their own pass (blur/sampling/compute/composite) return a structured
 * error pointing at the offending nodes. This compiler supports a single pass.
 */
import type { Graph } from "../types";
import { getNode } from "../nodelib";
import { topoSort } from "../validator";

export interface FilterPipeline {
  abi: string;
  kind: "filter";
  passes: Array<{
    id: string;
    kind: "compute";
    entry: string;
    workgroup: [number, number, number];
    shader: string;
    inputs: string[];
    output: string;
  }>;
  params: Array<{ id: string; binding: number; type: "f32" | "vec2" | "vec4" }>;
  intermediates: string[];
}

export interface FilterShader {
  path: string;
  source: string;
}

export type FilterCompileResult =
  | { ok: true; wgsl: string; shaders: FilterShader[]; pipeline: FilterPipeline }
  | { ok: false; errors: Array<{ code: string; message: string; nodeId?: string }> };

const INLINE_OK = new Set(["input", "inline", "output"]);

export function compileFilter(graph: Graph): FilterCompileResult {
  const errors: Array<{ code: string; message: string; nodeId?: string }> = [];
  const byId = new Map(graph.nodes.map((nd) => [nd.id, nd]));

  // reject nodes that can't be inline-fused in v1
  for (const node of graph.nodes) {
    const spec = getNode(node.type);
    if (!spec) {
      errors.push({ code: "unknown_node", message: `Unknown node "${node.type}"`, nodeId: node.id });
      continue;
    }
    if (!INLINE_OK.has(spec.passKind)) {
      errors.push({
        code: "multipass_unsupported",
        message: `Node "${node.type}" needs a dedicated ${spec.passKind} pass; multi-pass codegen is not yet supported`,
        nodeId: node.id,
      });
    }
  }
  if (errors.length) return { ok: false, errors };

  const order = topoSort(graph);
  const exprByNode = new Map<string, string>();
  const preludes = new Set<string>();

  const inputExprFor = (nodeId: string, portId: string): string => {
    const edge = graph.edges.find((e) => e.toNode === nodeId && e.toPort === portId);
    if (!edge) return "vec4<f32>(0.0)";
    return exprByNode.get(edge.fromNode) ?? "vec4<f32>(0.0)";
  };

  let finalExpr = "fx_src";

  for (const id of order) {
    const node = byId.get(id);
    if (!node) continue;
    const spec = getNode(node.type)!;
    if (spec.prelude) preludes.add(spec.prelude);

    if (node.type === "Output") {
      finalExpr = inputExprFor(id, "in");
      continue;
    }
    if (!spec.emitInline) {
      exprByNode.set(id, "vec4<f32>(0.0)");
      continue;
    }
    const inputs: Record<string, string> = {};
    for (const port of spec.inputs) inputs[port.id] = inputExprFor(id, port.id);
    exprByNode.set(id, spec.emitInline({ inputs, cfg: node.config ?? {} }));
  }

  // collect float/vec params referenced by Param nodes
  const usedParams = new Set<string>();
  for (const node of graph.nodes) {
    if (node.type === "Param" && typeof node.config?.param === "string") usedParams.add(node.config.param);
  }
  const params: FilterPipeline["params"] = [];
  let binding = 5; // 0..4 reserved for host uniforms + output
  const paramDecls: string[] = [];
  const paramLocals: string[] = [];
  for (const decl of graph.params) {
    if (!usedParams.has(decl.id)) continue;
    const wtype = decl.type === "color" ? "vec4" : decl.type === "vec2" ? "vec2" : "f32";
    params.push({ id: decl.id, binding, type: wtype });
    const wgslType = wtype === "f32" ? "f32" : wtype === "vec2" ? "vec2<f32>" : "vec4<f32>";
    paramDecls.push(`@group(0) @binding(${binding}) var<uniform> u_param_${decl.id}: ${wgslType};`);
    paramLocals.push(`  let param_${decl.id} = u_param_${decl.id};`);
    binding++;
  }

  const wgsl = [
    "// generated by @reelterminal/fxpkg filter compiler",
    ...[...preludes],
    "",
    "@group(0) @binding(0) var u_source: texture_2d<f32>;",
    "@group(0) @binding(1) var u_samp: sampler;",
    "@group(0) @binding(2) var<uniform> u_resolution: vec2<f32>;",
    "@group(0) @binding(3) var<uniform> u_time: f32;",
    "@group(0) @binding(4) var u_output: texture_storage_2d<rgba8unorm, write>;",
    ...paramDecls,
    "",
    "@compute @workgroup_size(8, 8, 1)",
    "fn main(@builtin(global_invocation_id) gid: vec3<u32>) {",
    "  let coord = vec2<i32>(gid.xy);",
    "  let dims = vec2<i32>(u_resolution);",
    "  if (coord.x >= dims.x || coord.y >= dims.y) { return; }",
    "  let fx_uv = vec2<f32>(coord) / u_resolution;",
    "  let fx_src = textureSampleLevel(u_source, u_samp, fx_uv, 0.0);",
    ...paramLocals,
    `  let fx_out = ${finalExpr};`,
    "  textureStore(u_output, coord, fx_out);",
    "}",
    "",
  ].join("\n");

  const pipeline: FilterPipeline = {
    abi: graph.abi,
    kind: "filter",
    passes: [
      {
        id: "main",
        kind: "compute",
        entry: "main",
        workgroup: [8, 8, 1],
        shader: "shaders/main.wgsl",
        inputs: ["source"],
        output: "final",
      },
    ],
    params,
    intermediates: [],
  };

  return { ok: true, wgsl, shaders: [{ path: "shaders/main.wgsl", source: wgsl }], pipeline };
}
